import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    position: 'relative',
  },
  header: {
    marginHorizontal: 10,
    marginTop: 10,
    paddingTop: 15,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    borderWidth: 1,
    borderRadius: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginBottom: 10,
  },
  naslov: {
    fontFamily: 'Roboto',
    fontWeight: '500',
    fontSize: 16,
    textTransform: 'capitalize',
  },
  podnaslov: {
    opacity: 0.5,
  },
  content: {
    paddingBottom: 4,
    paddingHorizontal: 15,
    position: 'relative',
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 20,
    fontFamily: 'Roboto',
  },
  btn: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a7c957',
  },
  kalorije: {
    marginTop: 0,
    fontSize: 35,
  },
  sections: {
    marginHorizontal: 10,
    padding: 15,
    flexDirection: 'column',
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 10,
    justifyContent: 'space-between',
  },
  section: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    padding: 10,
    borderRadius: 12,
  },
  opis: {
    fontSize: 20,
    fontFamily: 'Roboto',
  },
  slike: {
    height: 30,
    width: 30,
  },
  obroci: {
    marginHorizontal: 10,
    padding: 15,
    flexDirection: 'column',
    borderWidth: 1,
    borderRadius: 12,
    justifyContent: 'space-between',
    alignContent: 'center',
    marginBottom: 10,
    overflow: 'hidden',
  },
  obrok: {
    marginHorizontal: 10,
    padding: 15,
    flexDirection: 'column',
    borderWidth: 1,
    borderRadius: 12,
    alignContent: 'center',
  },
  opis: {
    padding: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dodavanje: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    backgroundColor: 'white',
    padding: 15,
  },
  wrapper: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignContent: 'center',
    position: 'relative',
    paddingHorizontal: 55,
    gap: 20,
  },
  insider: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 12,
    alignContent: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginBottom: 5,
  },
  wrInputs: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 12,
    marginVertical: 10,
    alignContent: 'center',
    width: '100%',
    justifyContent: 'center',
    fontSize: 18,
  },
  jedinica: {
    paddingVertical: 17,
    paddingHorizontal: 8,
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 6,

    fontSize: 20,
    fontFamily: 'Roboto',
  },
});

export default styles;
