import { useState, memo } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  FlatList,
  TextInput,
} from 'react-native';
import styles from './hranaStyle';

const ListItem = memo(({ item, onPress }) => {
  return (
    <View style={styles.listItemContainer}>
      <View>
        <Text style={styles.itemText}>{item.hrana}</Text>
        <Text style={styles.calorieText}>
          <Text style={styles.itemText}>100g = </Text>
          {item.kalorije} kcal
        </Text>
      </View>
      <TouchableOpacity
        style={styles.buttonContainer}
        onPress={() => onPress(item.hrana, item.kalorije)}
      >
        <Text style={styles.buttonText}>Izračunaj</Text>
      </TouchableOpacity>
    </View>
  );
});

const Hrana = () => {
  const [listaHrane, setlistaHrane] = useState([
    { id: 1, kalorije: 51, hrana: 'ANANAS - svež' },
    { id: 2, kalorije: 95, hrana: 'ANANAS - konzerviran' },
    { id: 3, kalorije: 260, hrana: 'ANANAS - sušeni' },
    { id: 4, kalorije: 160, hrana: 'AVOKADO - svež' },
    { id: 5, kalorije: 650, hrana: 'BADEM - sirov' },
    { id: 6, kalorije: 565, hrana: 'BADEM - oljušten suvi' },
    { id: 7, kalorije: 597, hrana: 'BADEM - pečen' },
    { id: 8, kalorije: 79, hrana: 'BANANA - sveža cela' },
    { id: 9, kalorije: 92, hrana: 'BANANA - jestivi deo' },
    { id: 10, kalorije: 87, hrana: 'BANANA - sušena' },
    { id: 11, kalorije: 35, hrana: 'BOROVNICA - sveža' },
    { id: 12, kalorije: 656, hrana: 'BRAZILSKI - ORAH' },
    { id: 13, kalorije: 37, hrana: 'BRESKVA - sveža' },
    { id: 1234, kalorije: 50, hrana: 'BRESKVA - nektarina' },
    { id: 14, kalorije: 23, hrana: 'BRUSNICA - sveža' },
    { id: 15, kalorije: 308, hrana: 'BRUSNICA - sušena' },
    { id: 16, kalorije: 68, hrana: 'DUNJA - cela' },
    { id: 17, kalorije: 25, hrana: 'DUNJA - mesnati deo' },
    { id: 18, kalorije: 60, hrana: 'GROŽĐE - belo' },
    { id: 19, kalorije: 54, hrana: 'GROŽĐE - crno' },
    { id: 20, kalorije: 246, hrana: 'GROŽĐE - sušeno' },
    { id: 21, kalorije: 40, hrana: 'JABUKA - prosečno' },
    { id: 22, kalorije: 46, hrana: 'JABUKA - mesnati deo' },
    { id: 23, kalorije: 280, hrana: 'JABUKA - suva' },
    { id: 24, kalorije: 36, hrana: 'JAGODA - sveža' },
    { id: 25, kalorije: 109, hrana: 'JAGODA - sa šećerom' },
    { id: 26, kalorije: 51, hrana: 'KAJSIJA - sveža' },
    { id: 27, kalorije: 300, hrana: 'KAJSIJA - sušena' },
    { id: 28, kalorije: 245, hrana: 'KESTEN - pečen' },
    { id: 29, kalorije: 170, hrana: 'KESTEN - sirov' },
    { id: 30, kalorije: 570, hrana: 'KIKIRIKI - prženi' },
    { id: 31, kalorije: 547, hrana: 'KIKIRIKI - sirovi' },
    { id: 32, kalorije: 659, hrana: 'KOKOSOVO BRAŠNO - sa šećerom' },
    { id: 33, kalorije: 77, hrana: 'KOMPOT - ananas' },
    { id: 34, kalorije: 126, hrana: 'KOMPOT - borovnica' },
    { id: 35, kalorije: 87, hrana: 'KOMPOT - breskva' },
    { id: 36, kalorije: 88, hrana: 'KOMPOT - kajsija' },
    { id: 37, kalorije: 77, hrana: 'KOMPOT - kruška' },
    { id: 38, kalorije: 70, hrana: 'KOMPOT - šljiva' },
    {
      id: 39,
      kalorije: 78,
      hrana: 'KOMPOT - od trešanja ili višanja',
    },
    { id: 40, kalorije: 29, hrana: 'KRUŠKA - sveža' },
    { id: 41, kalorije: 41, hrana: 'KRUŠKA - mesnati deo' },
    { id: 42, kalorije: 0, hrana: 'LEŠNIK - sirovi' },
    { id: 43, kalorije: 657, hrana: 'LEŠNIK - sušen' },
    { id: 44, kalorije: 646, hrana: 'LEŠNIK - pečen' },
    { id: 45, kalorije: 547, hrana: 'MAK - sušen' },
    { id: 46, kalorije: 59, hrana: 'MANGO - mesnati deo' },
    { id: 47, kalorije: 295, hrana: 'MANGO - sušen' },
    { id: 48, kalorije: 156, hrana: 'MASLINA - crna sveža' },
    { id: 49, kalorije: 216, hrana: 'MASLINA - zelena sveža' },
    { id: 50, kalorije: 28, hrana: 'MUŠMULA - cela' },
    { id: 51, kalorije: 42, hrana: 'MUŠMULA - mesnati deo' },
    { id: 52, kalorije: 41, hrana: 'NARANDŽA - crvena' },
    { id: 53, kalorije: 529, hrana: 'ORAH - sirov' },
    { id: 54, kalorije: 649, hrana: 'ORAH - suvi' },
    { id: 55, kalorije: 32, hrana: 'PAPAJA - sveža' },
    { id: 56, kalorije: 215, hrana: 'PAPAJA - suva' },
    { id: 57, kalorije: 568, hrana: 'PISTAĆI - slani' },
    { id: 58, kalorije: 26, hrana: 'RIBIZLA - bela' },
    { id: 59, kalorije: 28, hrana: 'RIBIZLA - crna' },
    { id: 60, kalorije: 21, hrana: 'RIBIZLE - crvena' },
    { id: 61, kalorije: 323, hrana: 'ROGAČ - mleveni' },
    { id: 62, kalorije: 213, hrana: 'SMOKVE - sušene' },
    { id: 63, kalorije: 170, hrana: 'ŠIPAK - sušeni mleveni' },
    { id: 64, kalorije: 50, hrana: 'ŠLJIVA - sveža' },
    { id: 65, kalorije: 268, hrana: 'ŠLJIVA - suva' },
    { id: 66, kalorije: 34, hrana: 'ARTIČOKA - jestivi deo' },
    { id: 67, kalorije: 17, hrana: 'ARTIČOKA - mladi cvetovi' },
    { id: 68, kalorije: 23, hrana: 'BOB - svež' },
    { id: 69, kalorije: 343, hrana: 'BOB - suv' },
    { id: 70, kalorije: 18, hrana: 'BORANIJA - zelena' },
    { id: 71, kalorije: 28, hrana: 'BORANIJA - žuta' },
    { id: 72, kalorije: 34, hrana: 'BROKOLI - sirov' },
    { id: 73, kalorije: 15, hrana: 'BUNDEVA - žuta' },
    { id: 74, kalorije: 23, hrana: 'CELER - koren' },
    { id: 75, kalorije: 12, hrana: 'CELER - list' },
    { id: 76, kalorije: 36, hrana: 'CVEKLA - konzervisana' },
    { id: 77, kalorije: 67, hrana: 'GRAŠAK - mladi' },
    { id: 78, kalorije: 53, hrana: 'GRAŠAK - smrznuti' },
    { id: 79, kalorije: 339, hrana: 'GRAŠAK - suvi' },
    { id: 80, kalorije: 32, hrana: 'KARFIOL - kuvan' },
    { id: 81, kalorije: 41, hrana: 'KELJ - lisnati' },
    { id: 82, kalorije: 27, hrana: 'KOMORAČ - list' },
    { id: 83, kalorije: 10, hrana: 'KRASTAVAC - kiseli' },
    { id: 84, kalorije: 14, hrana: 'KRASTAVAC - svež' },
    { id: 85, kalorije: 71, hrana: 'KROMPIR - mladi' },
    { id: 86, kalorije: 99, hrana: 'KROMPIR - mladi pečen' },
    { id: 87, kalorije: 146, hrana: 'KROMPIR - pečen' },
    { id: 88, kalorije: 220, hrana: 'KROMPIR - pomfrit' },
    { id: 89, kalorije: 100, hrana: 'KROMPIR - pire' },
    { id: 90, kalorije: 101, hrana: 'KROMPIR - restovan' },
    { id: 91, kalorije: 87, hrana: 'KROMPIR - sirov' },
    { id: 92, kalorije: 20, hrana: 'KUPUS - crveni' },
    { id: 93, kalorije: 22, hrana: 'KUPUS - beli' },
    { id: 94, kalorije: 12, hrana: 'KUPUS - kineski' },
    { id: 95, kalorije: 12, hrana: 'KUPUS - kiseli' },
    { id: 96, kalorije: 45, hrana: 'MASLAČAK - list' },
    { id: 97, kalorije: 28, hrana: 'PAPRIKA - crvena' },
    { id: 98, kalorije: 15, hrana: 'PAPRIKA - kisela' },
    { id: 99, kalorije: 20, hrana: 'PAPRIKA - zelena' },
    { id: 100, kalorije: 22, hrana: 'PAPRIKA - žuta slatka' },
    { id: 101, kalorije: 19, hrana: 'PARADAJZ - svež' },
    { id: 102, kalorije: 39, hrana: 'PARADAJZ - kuvan' },
    { id: 103, kalorije: 43, hrana: 'PARADAJZ - pire' },
    { id: 104, kalorije: 260, hrana: 'PASULJ - beli' },
    { id: 105, kalorije: 110, hrana: 'PASULJ - mladi' },
    { id: 106, kalorije: 273, hrana: 'PASULJ - šareni' },
    { id: 107, kalorije: 74, hrana: 'PAŠKANAT - zelen' },
    { id: 108, kalorije: 33, hrana: 'PEČURKE - sveže prosečno' },
    { id: 109, kalorije: 16, hrana: 'PEČURKE - sveži šampinjoni' },
    {
      id: 110,
      kalorije: 22,
      hrana: 'PEČURKE - konzervirane šampinjoni',
    },
    { id: 111, kalorije: 25, hrana: 'PEČURKE - vrganj' },
    { id: 112, kalorije: 147, hrana: 'PERČUKE - sušene' },
    { id: 113, kalorije: 296, hrana: 'PEČURKE ŠITAKI - sušene' },
    { id: 114, kalorije: 32, hrana: 'PRAZILUK - beli deo' },
    { id: 115, kalorije: 28, hrana: 'PRAZILUK - ceo' },
    { id: 116, kalorije: 16, hrana: 'RADIČ - crveni' },
    { id: 117, kalorije: 59, hrana: 'RADIČ - zeleni' },
    { id: 118, kalorije: 60, hrana: 'REN - ribani sa sirćetom' },
    { id: 119, kalorije: 20, hrana: 'REN - sirovi' },
    { id: 120, kalorije: 20, hrana: 'REPA - bela' },
    { id: 121, kalorije: 26, hrana: 'REPA - koren' },
    { id: 122, kalorije: 42, hrana: 'REPA - kisela' },
    { id: 123, kalorije: 21, hrana: 'REPA - sveža' },
    { id: 124, kalorije: 43, hrana: 'ROTKVA - bela' },
    { id: 125, kalorije: 28, hrana: 'ROTKVA - crna' },
    { id: 126, kalorije: 15, hrana: 'ROTKVICA - crvena' },
    { id: 127, kalorije: 18, hrana: 'SALATA - endvija' },
    { id: 128, kalorije: 12, hrana: 'SALATA - puterica' },
    { id: 129, kalorije: 14, hrana: 'SALATA - zelena iceberg' },
    { id: 130, kalorije: 12, hrana: 'SPANAĆ - svež' },
    { id: 131, kalorije: 24, hrana: 'SPANAĆ - kuvan' },
    { id: 132, kalorije: 41, hrana: 'ŠARGAREPA - kuvana' },
    { id: 133, kalorije: 31, hrana: 'ŠARGAREPA - konzervirana' },
    { id: 134, kalorije: 53, hrana: 'JOGURT - 2%mm' },
    { id: 135, kalorije: 34, hrana: 'JOGURT - 05% mm' },
    { id: 136, kalorije: 40, hrana: 'JOGURT - 09% mm "Ella"' },
    { id: 137, kalorije: 41, hrana: 'JOGURT - 1% mm' },
    { id: 138, kalorije: 45, hrana: 'JOGURT - 15%mm' },
    { id: 139, kalorije: 99, hrana: 'JOGURT - 32 % mm voćni' },
    { id: 140, kalorije: 62, hrana: 'JOGURT - 32% mm' },
    { id: 141, kalorije: 572, hrana: 'KAJMAK - zreli' },
    { id: 142, kalorije: 255, hrana: 'KAJMAK - mladi' },
    { id: 143, kalorije: 64, hrana: 'KISELO MLEKO - kravlje' },
    { id: 144, kalorije: 121, hrana: 'KISELO MLEKO - ovčije' },
    { id: 145, kalorije: 217, hrana: 'MILERAM - 215% mm' },
    { id: 146, kalorije: 64, hrana: 'MLEKO - čokoladno 1% mm' },
    { id: 147, kalorije: 92, hrana: 'MLEKO - čokoladno 32% mm' },
    { id: 148, kalorije: 48, hrana: 'MLEKO - kobilje' },
    { id: 149, kalorije: 73, hrana: 'MLEKO - kozije' },
    { id: 150, kalorije: 39, hrana: 'MLEKO - kravlje 0.9% mm' },
    { id: 151, kalorije: 46, hrana: 'MLEKO - kravlje 15% mm' },
    { id: 152, kalorije: 50, hrana: 'MLEKO - kravlje 18% mm' },
    { id: 153, kalorije: 51, hrana: 'MLEKO - kravlje 22% mm' },
    { id: 154, kalorije: 58, hrana: 'MLEKO - kravlje 28% mm' },
    { id: 155, kalorije: 62, hrana: 'MLEKO - kravlje 32%mm' },
    { id: 156, kalorije: 61, hrana: 'MLEKO - kravlje 33% mm' },
    { id: 157, kalorije: 161, hrana: 'MLEKO - kravlje kondenzovano' },
    {
      id: 158,
      kalorije: 183,
      hrana: 'MLEKO - kravlje kondenzovano 10% mm',
    },
    {
      id: 159,
      kalorije: 137,
      hrana: 'MLEKO - kravlje kondenzovano 7.5% mm',
    },
    { id: 160, kalorije: 33, hrana: 'MLEKO - kravlje obrano' },
    { id: 5432, kalorije: 64, hrana: 'MLEKO - kravlje punomasno' },
    {
      id: 4321,
      kalorije: 134,
      hrana: 'MLEKO - kravlje punomasno evaporisano nezašećereno',
    },
    {
      id: 161,
      kalorije: 322,
      hrana: 'MLEKO - kravlje punomasno kondenzovano zašećereno',
    },
    {
      id: 162,
      kalorije: 67,
      hrana: 'MLEKO - kravlje sveže pomuženo',
    },
    { id: 163, kalorije: 99, hrana: 'MLEKO - ovčije' },
    { id: 164, kalorije: 528, hrana: 'MLEKO - sojino' },
    { id: 165, kalorije: 362, hrana: 'MLEKO - u prahu obrano' },
    { id: 166, kalorije: 490, hrana: 'MLEKO - u prahu punomasno' },
    { id: 167, kalorije: 69, hrana: 'MLEKO - majčino' },
    { id: 168, kalorije: 119, hrana: 'PAVLAKA KISELA - 10% mm' },
    { id: 169, kalorije: 126, hrana: 'PAVLAKA KISELA - 12% mm' },
    { id: 170, kalorije: 210, hrana: 'PAVLAKA KISELA - 20% mm' },
    { id: 171, kalorije: 293, hrana: 'PAVLAKA KISELA - 30% mm' },
    { id: 172, kalorije: 300, hrana: 'PAVLAKA SLATKA - 15%mm' },
    {
      id: 173,
      kalorije: 316,
      hrana: 'PAVLAKA SLATKA - 15%mm umućena',
    },
    { id: 174, kalorije: 355, hrana: 'SIR - TOPLJENI' },
    { id: 175, kalorije: 352, hrana: 'SIR - 20% mm' },
    {
      id: 176,
      kalorije: 370,
      hrana: 'SIR - BILJNI (tipa kačkavalja i sl.)',
    },
    { id: 177, kalorije: 263, hrana: 'SIR - brie' },
    { id: 178, kalorije: 284, hrana: 'SIR - camembert' },
    { id: 179, kalorije: 401, hrana: 'SIR - cheddar' },
    { id: 180, kalorije: 345, hrana: 'SIR - edamer 40%mm' },
    { id: 181, kalorije: 386, hrana: 'SIR - ementaler' },
    { id: 182, kalorije: 370, hrana: 'SIR - feta kravlja' },
    { id: 183, kalorije: 380, hrana: 'SIR - feta ovčija' },
    { id: 184, kalorije: 392, hrana: 'SIR - gauda punomasni' },
    { id: 185, kalorije: 422, hrana: 'SIR - gervais 60%mm' },
    { id: 186, kalorije: 346, hrana: 'SIR - gorgonzola' },
    { id: 187, kalorije: 390, hrana: 'SIR - kačkavalj' },
    { id: 188, kalorije: 320, hrana: 'SIR - koziji' },
    { id: 189, kalorije: 97, hrana: 'SIR - kravlji svež' },
    { id: 190, kalorije: 97, hrana: 'SIR - kravlji svež 10%mm' },
    { id: 191, kalorije: 110, hrana: 'SIR - kravlji svež 20%mm' },
    { id: 192, kalorije: 158, hrana: 'SIR - kravlji svež 40%mm' },
    { id: 193, kalorije: 389, hrana: 'SIR - kravlji svež 50%mm' },
    { id: 194, kalorije: 73, hrana: 'SIR - kravlji svež' },
    { id: 195, kalorije: 95, hrana: 'SIR - kravlji sveži (cottage)' },
    { id: 196, kalorije: 118, hrana: 'SIR - kravlji svež beli' },
    { id: 197, kalorije: 370, hrana: 'SIR - masni 40%' },
    { id: 198, kalorije: 224, hrana: 'SIR - mozzarella' },
    { id: 199, kalorije: 174, hrana: 'SIR - namaz 20%mm' },
    { id: 200, kalorije: 223, hrana: 'SIR - namaz 30% mm' },
    { id: 201, kalorije: 219, hrana: 'SIR - namaz 30%mm' },
    { id: 202, kalorije: 251, hrana: 'SIR - namaz 40%mm' },
    { id: 203, kalorije: 250, hrana: 'SIR - TOFU (tipa kačkavalja i sl.)' },
    { id: 204, kalorije: 392, hrana: 'SIR - parmezan' },
    { id: 205, kalorije: 371, hrana: 'SIR - punomasni' },
    { id: 206, kalorije: 341, hrana: 'SIR - punomasni 35%' },
    { id: 207, kalorije: 359, hrana: 'SIR - roquefort' },
    { id: 208, kalorije: 305, hrana: 'SIR - topljeni 45%mm' },
    { id: 209, kalorije: 322, hrana: 'SIR - trapist' },
    { id: 210, kalorije: 428, hrana: 'SIR - zreli' },
    { id: 211, kalorije: 59, hrana: 'SIR -"Ella" 0% mm' },
    { id: 212, kalorije: 349, hrana: 'SURUTKA - u prahu' },
    { id: 213, kalorije: 86, hrana: 'BUBREZI - goveđi' },
    { id: 214, kalorije: 90, hrana: 'BUBREZI - jagnjeći svinjski' },
    { id: 215, kalorije: 118, hrana: 'BUBREZI - pileći' },
    { id: 216, kalorije: 524, hrana: 'ČVARCI - presovani' },
    { id: 217, kalorije: 136, hrana: 'ĆURETINA - belo meso' },
    { id: 218, kalorije: 143, hrana: 'ĆURETINA - prosečno' },
    { id: 219, kalorije: 190, hrana: 'ĆURETINA - crno meso batak' },
    { id: 220, kalorije: 179, hrana: 'GOVEDINA - but' },
    { id: 221, kalorije: 106, hrana: 'GOVEDINA - filet' },
    { id: 222, kalorije: 410, hrana: 'GOVEDINA - masna' },
    { id: 223, kalorije: 228, hrana: 'GOVEDINA - jezik' },
    { id: 224, kalorije: 272, hrana: 'GOVEDINA - kuk' },
    { id: 225, kalorije: 771, hrana: 'GOVEDINA - loj' },
    { id: 226, kalorije: 131, hrana: 'GOVEDINA - nemasna' },
    { id: 227, kalorije: 252, hrana: 'GOVEDINA - prsa' },
    { id: 228, kalorije: 290, hrana: 'GOVEDINA - rostbraten' },
    { id: 229, kalorije: 143, hrana: 'GOVEDINA - sa 25% kosti' },
    { id: 230, kalorije: 218, hrana: 'GOVEDINA - srednje masna' },
    { id: 231, kalorije: 223, hrana: 'GOVEDINA - u konzervi' },
    { id: 232, kalorije: 354, hrana: 'GUSKA - masna' },
    { id: 233, kalorije: 360, hrana: 'HAMBURGER - ispečen bez peciva' },
    { id: 234, kalorije: 245, hrana: 'JAGNJETINA - grudi' },
    { id: 235, kalorije: 163, hrana: 'JAGNJETINA - kotleti' },
    { id: 236, kalorije: 279, hrana: 'JAGNJETINA - masna' },
    { id: 237, kalorije: 124, hrana: 'JAGNJETINA - file' },
    { id: 238, kalorije: 211, hrana: 'JAGNJETINA - srednje masna' },
    { id: 239, kalorije: 163, hrana: 'JETRA - goveđa' },
    { id: 240, kalorije: 180, hrana: 'JETRA - guščija' },
    { id: 241, kalorije: 131, hrana: 'JETRA - kokošija' },
    { id: 242, kalorije: 128, hrana: 'JETRA - pileća' },
    { id: 243, kalorije: 154, hrana: 'JETRA - svinjska' },
    { id: 244, kalorije: 153, hrana: 'JETRA - teleća' },
    { id: 245, kalorije: 228, hrana: 'JEZIK - goveđi telećisvinjski' },
    { id: 246, kalorije: 155, hrana: 'JUNETINA - manje masna' },
    { id: 247, kalorije: 202, hrana: 'JUNETINA - srednjemasna mesa' },
    { id: 248, kalorije: 491, hrana: 'KOBASICA - čajna' },
    { id: 249, kalorije: 484, hrana: 'KOBASICA - debrecina pržena' },
    { id: 250, kalorije: 256, hrana: 'KOBASICA - frankfurtska' },
    { id: 251, kalorije: 394, hrana: 'KOBASICA - govedina i svinjetina' },
    { id: 252, kalorije: 232, hrana: 'KOBASICA - goveđa' },
    { id: 253, kalorije: 143, hrana: 'KOBASICA - goveđa' },
    { id: 254, kalorije: 530, hrana: 'KOBASICA - kulen' },
    { id: 255, kalorije: 346, hrana: 'KOBASICA - lovačka' },
    { id: 256, kalorije: 401, hrana: 'KOBASICA - prosečno' },
    { id: 257, kalorije: 418, hrana: 'KOBASICA - roštiljska na ulju i vodi' },
    { id: 258, kalorije: 523, hrana: 'KOBASICA - sušena dimljena' },
    { id: 259, kalorije: 364, hrana: 'KOBASICA - svinjska' },
    { id: 260, kalorije: 513, hrana: 'KOBASICA - svinjska (suva)' },
    { id: 261, kalorije: 524, hrana: 'KOBASICE - domaće mesne' },
    { id: 262, kalorije: 320, hrana: 'KOBASICE - pržene' },
    { id: 263, kalorije: 118, hrana: 'PILETINA - belo meso' },
    { id: 264, kalorije: 186, hrana: 'PILETINA - cela prosečno' },
    { id: 265, kalorije: 128, hrana: 'PILETINA - crno meso (batak)' },
    { id: 266, kalorije: 345, hrana: 'MESNI NAREZAK - od svinjskog mesa' },
    { id: 267, kalorije: 338, hrana: 'MESNI NAREZAK - svinjsko + goveđe' },
    { id: 268, kalorije: 316, hrana: 'MLEVENO MESO - mešano' },
    { id: 269, kalorije: 110, hrana: 'MOZAK - teleći / jagnjeći' },
    { id: 270, kalorije: 299, hrana: 'OVČETINA - prosečno' },
    { id: 271, kalorije: 230, hrana: 'OVČETINA - but' },
    { id: 272, kalorije: 348, hrana: 'OVČETINA - kotleti' },
    { id: 273, kalorije: 798, hrana: 'OVČETINA - loj' },
    { id: 274, kalorije: 414, hrana: 'OVČETINA - masna' },
    { id: 275, kalorije: 206, hrana: 'OVČETINA - mršava' },
    { id: 276, kalorije: 289, hrana: 'OVČETINA - plećka' },
    { id: 277, kalorije: 237, hrana: 'OVČETINA - polumasna' },
    { id: 278, kalorije: 204, hrana: 'OVČETINA - sa 17% kosti' },
    { id: 279, kalorije: 124, hrana: 'PAČETINA - bez kože' },
    { id: 280, kalorije: 198, hrana: 'PAČETINA - nemasna' },
    { id: 281, kalorije: 348, hrana: 'PAČETINA - srednje masno' },
    { id: 282, kalorije: 332, hrana: 'PAŠTETA - jetrena svinjska' },
    { id: 283, kalorije: 128, hrana: 'PAŠTETA - pileća' },
    { id: 284, kalorije: 233, hrana: 'PATKA - divlja' },
    { id: 285, kalorije: 122, hrana: 'PATKA - nemasna' },
    { id: 286, kalorije: 341, hrana: 'PATKA - srednje masna' },
    { id: 287, kalorije: 430, hrana: 'PATKA - tovljena' },
    { id: 288, kalorije: 116, hrana: 'PILE - belo meso bez kostiju' },
    { id: 289, kalorije: 145, hrana: 'PILE - celo prosečno' },
    { id: 290, kalorije: 126, hrana: 'PILE - crno meso - batak' },
    { id: 291, kalorije: 142, hrana: 'PRASETINA - mršava' },
    { id: 292, kalorije: 75, hrana: 'PUŽ - vinogradski' },
    { id: 293, kalorije: 415, hrana: 'SALAMA - mortadela' },
    { id: 294, kalorije: 417, hrana: 'SALAMA - goveđa trajna' },
    { id: 295, kalorije: 265, hrana: 'SALAMA - mortadela' },
    { id: 296, kalorije: 253, hrana: 'SALAMA - parizer' },
    { id: 297, kalorije: 197, hrana: 'SALAMA - pileća ćureća' },
    { id: 298, kalorije: 564, hrana: 'SALAMA - prosečno' },
    { id: 299, kalorije: 408, hrana: 'SALAMA - šunkarica' },
    { id: 300, kalorije: 465, hrana: 'SALAMA - trajna (svinjsko)' },
    { id: 301, kalorije: 875, hrana: 'SLANINA - bez mišićnog tkiva' },
    { id: 302, kalorije: 575, hrana: 'SLANINA - mesnata kuvana' },
    { id: 303, kalorije: 622, hrana: 'SLANINA - polumasna' },
    { id: 304, kalorije: 658, hrana: 'SLANINA - prošarana' },
    { id: 305, kalorije: 713, hrana: 'SLANINA - suva' },
    { id: 306, kalorije: 797, hrana: 'SLANINA - suva masna' },
    { id: 307, kalorije: 506, hrana: 'SLANINA - suva mesnata' },
    { id: 308, kalorije: 784, hrana: 'SLANINA - svinjska sirova' },
    { id: 309, kalorije: 782, hrana: 'SLANINA - svinjska sirova soljena' },
    { id: 310, kalorije: 108, hrana: 'SRCE - goveđe' },
    { id: 311, kalorije: 119, hrana: 'SRCE - jagnjeće' },
    { id: 312, kalorije: 93, hrana: 'SRCE - svinjsko' },
    { id: 313, kalorije: 167, hrana: 'SRCE - teleće' },
    { id: 314, kalorije: 168, hrana: 'SVINJETINA - but' },
    { id: 315, kalorije: 176, hrana: 'SVINJETINA - file' },
    { id: 316, kalorije: 199, hrana: 'SVINJETINA - glava noge' },
    { id: 317, kalorije: 563, hrana: 'SVINJETINA - jako masno' },
    { id: 318, kalorije: 135, hrana: 'SVINJETINA - jetra' },
    { id: 319, kalorije: 225, hrana: 'SVINJETINA - jetra pečena' },
    { id: 320, kalorije: 228, hrana: 'SVINJETINA - jezik' },
    { id: 321, kalorije: 330, hrana: 'SVINJETINA - kare' },
    { id: 322, kalorije: 334, hrana: 'SVINJETINA - kotlet' },
    { id: 323, kalorije: 605, hrana: 'SVINJETINA - kožice suve' },
    { id: 324, kalorije: 459, hrana: 'SVINJETINA - masna' },
    { id: 325, kalorije: 120, hrana: 'SVINJETINA - mozak' },
    { id: 326, kalorije: 182, hrana: 'SVINJETINA - mršava' },
    { id: 327, kalorije: 202, hrana: 'SVINJETINA - nemasna kuvana' },
    { id: 328, kalorije: 207, hrana: 'SVINJETINA - noga sušena' },
    { id: 329, kalorije: 140, hrana: 'SVINJETINA - pečenica' },
    { id: 330, kalorije: 395, hrana: 'SVINJETINA - plećka' },
    { id: 331, kalorije: 291, hrana: 'SVINJETINA - polumasno' },
    { id: 332, kalorije: 388, hrana: 'SVINJETINA - prosečno' },
    { id: 333, kalorije: 423, hrana: 'SVINJETINA - rebarca pečena' },
    { id: 334, kalorije: 280, hrana: 'SVINJETINA - srednje masna' },
    { id: 335, kalorije: 350, hrana: 'SVINJETINA - srednje masno' },
    { id: 336, kalorije: 326, hrana: 'SVINJETINA - sušena' },
    { id: 337, kalorije: 144, hrana: 'SVINJETINA - sušeni kare' },
    { id: 338, kalorije: 258, hrana: 'SVINJETINA - švargla' },
    { id: 339, kalorije: 368, hrana: 'SVINJETINA - vrat' },
    { id: 340, kalorije: 153, hrana: 'ŠUNKA - bez masti' },
    { id: 341, kalorije: 128, hrana: 'ŠUNKA - ćureća / pileća' },
    { id: 342, kalorije: 412, hrana: 'ŠUNKA - dimljena kuvana' },
    { id: 343, kalorije: 434, hrana: 'ŠUNKA - dimljena soljena sušena' },
    { id: 344, kalorije: 385, hrana: 'ŠUNKA - dimljena sirova' },
    { id: 345, kalorije: 282, hrana: 'ŠUNKA - kuvana' },
    { id: 346, kalorije: 430, hrana: 'ŠUNKA - kuvana masna' },
    { id: 347, kalorije: 264, hrana: 'ŠUNKA - kuvana slana' },
    { id: 348, kalorije: 129, hrana: 'ŠUNKA - praška' },
    { id: 349, kalorije: 129, hrana: 'ŠUNKA - presovana bez masti' },
    { id: 350, kalorije: 395, hrana: 'ŠUNKA - prosečno' },
    { id: 351, kalorije: 335, hrana: 'ŠUNKA - srednje masna' },
    { id: 352, kalorije: 263, hrana: 'ŠUNKA - stišnjena u omotu' },
    { id: 353, kalorije: 129, hrana: 'TELETINA - jetra' },
    { id: 354, kalorije: 228, hrana: 'TELETINA - jezik' },
    { id: 355, kalorije: 185, hrana: 'TELETINA - kolenica' },
    { id: 356, kalorije: 163, hrana: 'TELETINA - kotleti' },
    { id: 357, kalorije: 204, hrana: 'TELETINA - masna' },
    { id: 358, kalorije: 120, hrana: 'TELETINA - mozak' },
    { id: 359, kalorije: 115, hrana: 'TELETINA - nemasna' },
    { id: 360, kalorije: 167, hrana: 'TELETINA - srce' },
    { id: 361, kalorije: 163, hrana: 'TELETINA - srednje masna' },
    { id: 362, kalorije: 327, hrana: 'VIRŠLE - od mešanog mesa' },
    { id: 363, kalorije: 258, hrana: 'VIRŠLE - od pilećeg mesa' },
    { id: 364, kalorije: 203, hrana: 'BAKALAR - pljeskavica panirana' },
    { id: 365, kalorije: 338, hrana: 'BAKALAR - suvi' },
    { id: 366, kalorije: 212, hrana: 'BAKALAR - štapići panirani' },
    { id: 367, kalorije: 154, hrana: 'BELE RIBE - prosečno' },
    { id: 368, kalorije: 325, hrana: 'GIRICE - pečene' },
    { id: 369, kalorije: 350, hrana: 'GIRICE - pržene' },
    { id: 370, kalorije: 232, hrana: 'HARINGA - dimljena' },
    { id: 371, kalorije: 211, hrana: 'HARINGA - dimljena bez kosti' },
    { id: 372, kalorije: 175, hrana: 'INĆUN - konzervisani' },
    { id: 373, kalorije: 328, hrana: 'JEGULJA - dimljena' },
    { id: 374, kalorije: 262, hrana: 'KAVIJAR - granulirani' },
    { id: 375, kalorije: 125, hrana: 'KIRNJA - dubinska' },
    { id: 376, kalorije: 91, hrana: 'KOZICA - velika' },
    {
      id: 377,
      kalorije: 255,
      hrana: 'LIGNJA - pljeskavice sa sirom panirane na ulju',
    },
    { id: 378, kalorije: 203, hrana: 'LIGNJA - štapići panirani' },
    { id: 379, kalorije: 266, hrana: 'LIGNJA - štapići panirani na ulju' },
    { id: 380, kalorije: 168, hrana: 'LOSOS - u konzervi' },
    { id: 381, kalorije: 64, hrana: 'LUBIN - brancin' },
    { id: 382, kalorije: 195, hrana: 'PASTRMKA - kalifornijska' },
    { id: 383, kalorije: 86, hrana: 'PASTRMKA - potočna' },
    { id: 384, kalorije: 76, hrana: 'RAK - morski' },
    { id: 385, kalorije: 85, hrana: 'RAK - morski u konzervi' },
    { id: 386, kalorije: 96, hrana: 'RAK - morski kuvan' },
    { id: 387, kalorije: 74, hrana: 'RAK - rečni' },
    { id: 388, kalorije: 101, hrana: 'RAK - rečni u konzervi' },
    { id: 389, kalorije: 183, hrana: 'RAK - štapići panirani' },
    { id: 390, kalorije: 174, hrana: 'SARDINA - sveža' },
    { id: 391, kalorije: 207, hrana: 'SARDINE - konzervisane bez ulja' },
    { id: 392, kalorije: 334, hrana: 'SARDINE - konzervisani u ulju' },
    { id: 393, kalorije: 238, hrana: 'SKUŠA - dimljena' },
    { id: 394, kalorije: 184, hrana: 'SKUŠA - lokarda' },
    { id: 395, kalorije: 47, hrana: 'ŠKOLJKA - kuvana' },
    { id: 396, kalorije: 122, hrana: 'TUNA - pašteta' },
    { id: 397, kalorije: 117, hrana: 'TUNA - u aspiku' },
    { id: 398, kalorije: 284, hrana: 'TUNA - u konzervi' },
    { id: 399, kalorije: 293, hrana: 'TUNA - u ulju' },
    { id: 400, kalorije: 350, hrana: 'BRAŠNO PŠENIČNO - belo' },
    { id: 401, kalorije: 327, hrana: 'BRAŠNO PŠENIČNO - crno' },
    { id: 402, kalorije: 337, hrana: 'BRAŠNO PŠENIČNO - polubelo' },
    { id: 403, kalorije: 318, hrana: 'BRAŠNO PŠENIČNO - puno zrno' },
    { id: 404, kalorije: 364, hrana: 'BRAŠNO PŠENIČNO - tip 1100' },
    { id: 405, kalorije: 363, hrana: 'BRAŠNO PŠENIČNO - tip 400' },
    { id: 406, kalorije: 363, hrana: 'BRAŠNO PŠENIČNO - tip 600' },
    { id: 407, kalorije: 339, hrana: 'BRAŠNO PŠENIČNO - integralno' },
    { id: 408, kalorije: 356, hrana: 'BRAŠNO RAŽANO - belo' },
    { id: 409, kalorije: 350, hrana: 'BRAŠNO RAŽENO - crno' },
    { id: 410, kalorije: 263, hrana: 'BUREK - sa mesom' },
    { id: 411, kalorije: 246, hrana: 'BUREK - sa sirom' },
    { id: 412, kalorije: 550, hrana: 'GRISINI - integralni' },
    { id: 413, kalorije: 122, hrana: 'GRIZ PŠENIČNI - kuvani' },
    { id: 414, kalorije: 257, hrana: 'HLEB - crni' },
    { id: 415, kalorije: 206, hrana: 'HLEB - graham' },
    { id: 416, kalorije: 234, hrana: 'HLEB - heljda' },
    { id: 417, kalorije: 246, hrana: 'HLEB - ječmeni' },
    { id: 418, kalorije: 227, hrana: 'HLEB - kukuruzni' },
    { id: 419, kalorije: 230, hrana: 'HLEB - mešani (pšenica+raž)' },
    { id: 420, kalorije: 219, hrana: 'HLEB - mešani sa više raži' },
    { id: 421, kalorije: 269, hrana: 'HLEB - mlečni' },
    { id: 422, kalorije: 235, hrana: 'HLEB - polubeli 70%' },
    { id: 423, kalorije: 246, hrana: 'HLEB - pšenični 80%' },
    { id: 424, kalorije: 234, hrana: 'HLEB - pšenični beli' },
    { id: 425, kalorije: 239, hrana: 'HLEB - pšenični beli mlečni' },
    { id: 426, kalorije: 222, hrana: 'HLEB - pšenični crni' },
    { id: 427, kalorije: 241, hrana: 'HLEB - ražani' },
    { id: 428, kalorije: 365, hrana: 'HLEB - zdravlja' },
    { id: 429, kalorije: 369, hrana: 'KLICE - ječmene' },
    { id: 430, kalorije: 407, hrana: 'KLICE - kukuruzne' },
    { id: 431, kalorije: 287, hrana: 'KLICE - pšenične' },
    { id: 432, kalorije: 127, hrana: 'KUKURUZ - šećerac' },
    { id: 433, kalorije: 492, hrana: 'LAN - seme' },
    { id: 434, kalorije: 206, hrana: 'MEKINJE - pšenične' },
    { id: 435, kalorije: 314, hrana: 'MUSLI - prosečno' },
    { id: 436, kalorije: 368, hrana: 'PAHULJICE - kukuruzne (kornfleks)' },
    { id: 437, kalorije: 486, hrana: 'KEKS - sa čokoladnim prelivom' },
    { id: 438, kalorije: 390, hrana: 'PAHULJICE - ovsene' },
    { id: 439, kalorije: 375, hrana: 'PAHULJICE - pirinčane' },
    { id: 440, kalorije: 347, hrana: 'PAHULJICE - zobene' },
    { id: 441, kalorije: 73, hrana: 'PALENTA - kuvana' },
    { id: 442, kalorije: 116, hrana: 'PIRINAČ - glazirani kuvan' },
    { id: 443, kalorije: 357, hrana: 'PIRINAČ - glazirani sirov' },
    { id: 444, kalorije: 352, hrana: 'PIRINAČ - neljušten' },
    { id: 445, kalorije: 338, hrana: 'PIZZA - parče (salama kačkavalj kečap)' },
    { id: 446, kalorije: 330, hrana: 'PŠENICA - u zrnu' },
    { id: 447, kalorije: 216, hrana: 'PŠENICA/ŽITO - kuvano (žitovodašećer)' },
    { id: 448, kalorije: 423, hrana: 'SOJA - cele semenke sušene' },
    { id: 449, kalorije: 57, hrana: 'SOJA - klica' },
    { id: 450, kalorije: 357, hrana: 'SOJA - komadići ljuspice' },
    { id: 451, kalorije: 427, hrana: 'SOJA - u zrnu' },
    { id: 452, kalorije: 575, hrana: 'SUNCOKRET - semenka' },
    { id: 453, kalorije: 141, hrana: 'ŠPAGETI MAKARONI - kuvani,' },
    { id: 454, kalorije: 390, hrana: 'ŠPAGETI MAKARONI - prosečno,' },
    { id: 455, kalorije: 336, hrana: 'TESTENINA - bez jaja prosečno' },
    { id: 456, kalorije: 368, hrana: 'TESTENINA - sa jajima prosečno' },
    { id: 457, kalorije: 148, hrana: 'TESTO - kuvana testa' },
    { id: 458, kalorije: 547, hrana: 'TESTO - lisnato pečeno' },
    { id: 459, kalorije: 410, hrana: 'TESTO - mešano pečeno' },
    { id: 460, kalorije: 891, hrana: 'LOJ - goveđi' },
    { id: 461, kalorije: 892, hrana: 'LOJ - ovčiji' },
    { id: 462, kalorije: 729, hrana: 'MAJONEZ - "Delikates"' },
    { id: 463, kalorije: 454, hrana: 'MAJONEZ - dijet 50% ulja' },
    { id: 464, kalorije: 341, hrana: 'MAJONEZ - light' },
    { id: 465, kalorije: 730, hrana: 'MARGARIN - "Soft"' },
    { id: 466, kalorije: 225, hrana: 'MARGARIN - "Dobro jutro"' },
    { id: 467, kalorije: 380, hrana: 'MARGARIN - "Soft diet Minikal"' },
    { id: 468, kalorije: 885, hrana: 'MAST - ćureća' },
    { id: 469, kalorije: 906, hrana: 'MAST - guščija' },
    { id: 470, kalorije: 804, hrana: 'MAST - kokos' },
    { id: 471, kalorije: 885, hrana: 'MAST - kokošija' },
    { id: 472, kalorije: 885, hrana: 'MAST - pačija' },
    { id: 473, kalorije: 891, hrana: 'MAST - svinjska' },
    { id: 474, kalorije: 751, hrana: 'PUTER - neslani' },
    { id: 475, kalorije: 886, hrana: 'PUTER - od kikirikija' },
    { id: 476, kalorije: 751, hrana: 'PUTER - slani' },
    { id: 477, kalorije: 900, hrana: 'ULJE - kikirikijevo' },
    { id: 478, kalorije: 900, hrana: 'ULJE - kokosovo' },
    { id: 479, kalorije: 900, hrana: 'ULJE - kukuruzno' },
    { id: 480, kalorije: 896, hrana: 'ULJE - maslinovo' },
    { id: 481, kalorije: 900, hrana: 'ULJE - od kukuruznih klica' },
    { id: 482, kalorije: 900, hrana: 'ULJE - pšeničnih klica' },
    { id: 483, kalorije: 900, hrana: 'ULJE - repino' },
    { id: 484, kalorije: 900, hrana: 'ULJE - sojino' },
    { id: 485, kalorije: 900, hrana: 'ULJE - suncokretovo' },
    { id: 486, kalorije: 900, hrana: 'ULJE - susamovo' },
    { id: 487, kalorije: 158, hrana: 'KVASAC - pekarski' },
    { id: 488, kalorije: 295, hrana: 'KVASAC - suvi' },
    { id: 489, kalorije: 300, hrana: 'PAPRIKA - crvena mlevena' },
    { id: 490, kalorije: 400, hrana: 'PERŠUNOV LIST - sušeni' },
    { id: 491, kalorije: 12, hrana: 'SIRĆE - alkoholno' },
    { id: 492, kalorije: 13, hrana: 'SIRĆE - jabukovo' },
    { id: 493, kalorije: 14, hrana: 'SIRĆE - vinsko' },
    { id: 494, kalorije: 462, hrana: 'BISKVIT - masni' },
    { id: 495, kalorije: 351, hrana: 'BISKVIT - nemasni' },
    { id: 496, kalorije: 346, hrana: 'BOMBONI - gumeni' },
    { id: 497, kalorije: 440, hrana: 'BOMBONI - mlečna karamela' },
    { id: 498, kalorije: 381, hrana: 'BOMBONI - prosečno' },
    { id: 499, kalorije: 257, hrana: 'BOMBONI - žele' },
    { id: 500, kalorije: 471, hrana: 'BONŽITA - prosečno' },
    { id: 501, kalorije: 544, hrana: 'ČIPS - prosečno' },
    { id: 502, kalorije: 550, hrana: 'ČOKOLADA - mlečna' },
    { id: 503, kalorije: 512, hrana: 'ČOKOLADA - prosečno' },
    { id: 504, kalorije: 610, hrana: 'ČOKOLADA - s lešnicima' },
    { id: 505, kalorije: 534, hrana: 'ČOKOLADA - za kuvanje' },
    { id: 506, kalorije: 230, hrana: 'KAKAO - prah' },
    { id: 507, kalorije: 577, hrana: 'KEKS - integralni "O CAKE"' },
    { id: 508, kalorije: 507, hrana: 'KEKS - "NOBLICE"' },
    { id: 509, kalorije: 415, hrana: 'KEKS - "petit beurre"' },
    { id: 510, kalorije: 437, hrana: 'KEKS - "PLAZMA' },
    { id: 511, kalorije: 421, hrana: 'KEKS - prosečno' },
    { id: 512, kalorije: 97, hrana: 'JAJA - prepeličja' },
    { id: 513, kalorije: 142, hrana: 'JAJA - pileća' },
    { id: 514, kalorije: 213, hrana: 'JAJA - pileća kuvana' },
    { id: 515, kalorije: 162, hrana: 'JAJA - prepeličja kuvana' },
    { id: 516, kalorije: 143, hrana: 'JAJA - prepeličja tvrdo kuvana' },
    { id: 517, kalorije: 140, hrana: 'JAJA - prepeličja tvrdo kuvana' },
    {
      id: 518,
      kalorije: 181,
      hrana: 'JAJA - prepeličja tvrdo kuvana sa lukom',
    },
    { id: 519, kalorije: 68, hrana: 'JAJA - prepeličja sirova' },
    { id: 520, kalorije: 64, hrana: 'JAJA - prepeličja sirova bez ljuske' },
    { id: 521, kalorije: 143, hrana: 'JAJA - prepeličja sirova sa lukom' },
    { id: 522, kalorije: 158, hrana: 'KISELO MLEKO' },
    { id: 523, kalorije: 54, hrana: 'KISELA PAVLAKA 12% mm' },
    { id: 524, kalorije: 196, hrana: 'KISELA PAVLAKA 20% mm' },
    { id: 525, kalorije: 340, hrana: 'KISELA PAVLAKA 30% mm' },
    { id: 526, kalorije: 282, hrana: 'KOLAČI - prosečno' },
    { id: 527, kalorije: 111, hrana: 'KOMPOTI - prosečno' },
    { id: 528, kalorije: 415, hrana: 'KREKERI - slani sa susamom' },
    { id: 529, kalorije: 274, hrana: 'MARMELADA - prosečno' },
    { id: 530, kalorije: 320, hrana: 'MED - vrcani' },
    { id: 531, kalorije: 299, hrana: 'PERECE - slane' },
    { id: 532, kalorije: 157, hrana: 'SLADOLED - mlečni' },
    { id: 533, kalorije: 207, hrana: 'SLADOLED - prosečno' },
    { id: 534, kalorije: 274, hrana: 'SLATKO - prosečno' },
    { id: 535, kalorije: 400, hrana: 'ŠEĆER - kristal' },
    { id: 536, kalorije: 380, hrana: 'ŠEĆER - smeđi' },
    { id: 537, kalorije: 282, hrana: 'TORTA - čokoladna' },
    { id: 538, kalorije: 261, hrana: 'ŽELE - prosečno' },
    { id: 539, kalorije: 108, hrana: 'ČAJ - indijski' },
    { id: 540, kalorije: 58, hrana: 'KAFA - 2u1' },
    { id: 541, kalorije: 55, hrana: 'KAFA - "nescafe"' },
    { id: 542, kalorije: 70, hrana: 'KAFA - "nescafe strong" 3u1' },
    { id: 543, kalorije: 18, hrana: 'KAFA - sa mlekom 0.9 % mm' },
    { id: 544, kalorije: 23, hrana: 'KAFA - sa mlekom 1.5 % mm' },
    { id: 545, kalorije: 28, hrana: 'KAFA - sa mlekom 2.8 % mm' },
    { id: 546, kalorije: 287, hrana: 'KAFA - u zrnu' },
    { id: 547, kalorije: 230, hrana: 'KAKAO - u prahu' },
    { id: 548, kalorije: 228, hrana: 'KONJAK - 38 vol % alkohola' },
    { id: 549, kalorije: 375, hrana: 'KONJAK - 50 vol % alkohola' },
    { id: 550, kalorije: 175, hrana: 'RAKIJA - 25 vol % alkohola' },
    { id: 551, kalorije: 193, hrana: 'RAKIJA - 33 vol % alkohola' },
    { id: 552, kalorije: 350, hrana: 'RAKIJA - 50 vol % alkohola' },
    { id: 553, kalorije: 280, hrana: 'RUM - 40 vol % alkohola' },
    { id: 554, kalorije: 296, hrana: 'SIRUP - voćni prosečno' },
    { id: 555, kalorije: 53, hrana: 'SOK - ananas' },
    { id: 556, kalorije: 45, hrana: 'SOK - borovnica' },
    { id: 557, kalorije: 48, hrana: 'SOK - breskva' },
    { id: 558, kalorije: 36, hrana: 'SOK - cvekla' },
    { id: 559, kalorije: 48, hrana: 'SOK - grejpfrut' },
    { id: 560, kalorije: 63, hrana: 'SOK - grožđe' },
    { id: 561, kalorije: 47, hrana: 'SOK - jabuka' },
    { id: 562, kalorije: 44, hrana: 'SOK - jagoda' },
    { id: 563, kalorije: 45, hrana: 'SOK - kajsija' },
    { id: 564, kalorije: 50, hrana: 'SOK - kruška' },
    { id: 565, kalorije: 51, hrana: 'SOK - narandža' },
    { id: 566, kalorije: 68, hrana: 'SOK - paradajz (koncentrat 30%)' },
    { id: 567, kalorije: 85, hrana: 'VINO - belo stono' },
    { id: 568, kalorije: 80, hrana: 'VINO - crveno stono' },
  ]);

  const [kolicina, setKolicina] = useState('');
  const [searchText, setSearchText] = useState('');
  const [searchResult, setSearchResult] = useState(listaHrane);
  const [adjustedCalories, setAdjustedCalories] = useState(0);

  const renderItem = ({ item }) => {
    return <ListItem item={item} onPress={dodavanjeHrane} />;
  };

  const handleSearch = (text) => {
    setSearchText(text);

    const filteredResults = listaHrane.filter((item) =>
      item.hrana.toLowerCase().includes(text.toLowerCase())
    );
    setSearchResult(filteredResults);
  };

  const dodavanjeHrane = (naziv, kalorijeNa100g) => {
    if (!kolicina) {
      setAdjustedCalories(0);
    } else {
      const kolicinaFloat = parseFloat(kolicina);
      const calculatedCalories = parseFloat(
        ((kolicinaFloat / 100) * kalorijeNa100g).toFixed(2)
      );
      setAdjustedCalories(calculatedCalories);
    }
  };

  return (
    <View style={styles.container}>
      <View style={styles.inputRow}>
        <TextInput
          style={styles.textInput}
          placeholder="Pretraži.."
          onChangeText={handleSearch}
          value={searchText}
        />
        <View style={styles.quantityInputRow}>
          <TextInput
            style={styles.quantityInput}
            placeholder="Količina.."
            keyboardType="numeric"
            onChangeText={(text) => setKolicina(text)}
            value={kolicina}
          />
          <Text style={styles.unitText}>g</Text>
        </View>
      </View>
      <View style={styles.borderBottom}>
        <Text style={[styles.boldText, styles.borderBottom]}>
          Kalorije: {adjustedCalories} kcal
        </Text>
      </View>
      <FlatList
        data={searchResult}
        renderItem={renderItem}
        initialNumToRender={8}
        maxToRenderPerBatch={10}
        updateCellsBatchingPeriod={40}
        windowSize={12}
        removeClippedSubviews={true}
        keyExtractor={(item) => item.id}
      />
    </View>
  );
};

export default Hrana;
